project_id = "lypodfdlpbpjdsswmsni"

[functions.send-invitation-email]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.enrich-article]
verify_jwt = false

[functions.notify-new-competitor]
verify_jwt = false

[functions.add-market-topic]
verify_jwt = false

[functions.notify-new-journalist]
verify_jwt = false

[functions.notify-new-client]
verify_jwt = false

[functions.create-communique]
verify_jwt = false

[functions.generate-linkedin-post]
verify_jwt = false

[functions.journalist-enrichment-worker]
verify_jwt = false

[functions.fetch-organization-articles]
verify_jwt = false
