project_id = "lypodfdlpbpjdsswmsni"

# send-invitation-email : garde verify_jwt = false car on vérifie manuellement le JWT + le rôle admin
# Cela permet d'avoir un message d'erreur plus explicite si l'utilisateur n'est pas admin
[functions.send-invitation-email]
verify_jwt = false

# generate-embedding : garde verify_jwt = false car appelé par n8n avec une API key
[functions.generate-embedding]
verify_jwt = false

# enrich-article : garde verify_jwt = false car peut être appelé par des webhooks
[functions.enrich-article]
verify_jwt = false

# notify-new-competitor : garde verify_jwt = false car on vérifie manuellement le JWT
[functions.notify-new-competitor]
verify_jwt = false

[functions.add-market-topic]
verify_jwt = false